mybatis:
  mapper-locations: classpath:mapper/*.xml


    #spring:
    #  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://130.36.47.9:8088:3306/main
    #    username: root
  #    password: xRb(2*&LV

ds:
  master:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://130.36.47.9:8088:3306/main
    username: root
    password: xRb(2*&LV
